//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbCv1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEğitimlerim
    {
        public int Id { get; set; }
        public string Baslık { get; set; }
        public string AltBaslık { get; set; }
        public string AltBaslık2 { get; set; }
        public string GNO { get; set; }
        public string Tarih { get; set; }
        public string Resim { get; set; }
    }
}
